#!/usr/bin/with-contenv bash

echo "# plex_autoscan waiting for Plex service"
s6-svwait ../plex && sleep 1

echo "# plex_autoscan starting..."
exec s6-setuidgid abc python3 /plex_autoscan/scan.py server --loglevel=${PAS_LOG_LEVEL:-INFO}