#!/usr/bin/with-contenv bash

# If the first run completed successfully, we are done
if [ -e /.firstUnicornTransRunComplete ]; then
  exit 0
fi

echo [UNICORN TRANSCODER] Install Node10 and setup UnicornTranscoder
apt update && apt install git gpgv gnupg -y && curl -sL https://deb.nodesource.com/setup_10.x | bash - \
	&& apt install -y nodejs \
	&& cd /opt \
	&& git clone https://github.com/UnicornTranscoder/UnicornTranscoder \
	&& cd /opt/UnicornTranscoder \
	&& git checkout ${GIT_SHA:-d74bda5253dee27b795aec48c5d9958d58d97da6} \
    && mkdir -p /root/.npm \
    && npm install \
    && npm run install \
    && apt-get autoremove -y \
	&& rm -rf /var/lib/apt/lists/*
    
# permissions
chown -R abc:abc \
	/opt/UnicornTranscoder /root/.npm

touch ./firstUnicornTransRunComplete