sudo: true
dist: xenial
os: linux
language: shell

services:
  - docker

before_install:
- docker pull phusion/baseimage:18.04-1.0.0
- docker pull lsiobase/ubuntu:amd64-xenial
- docker pull alpine:3.10.2

env:
  global:
    - DOCKERHUB_LOGGING="nowaidavid/plex-media-server-stdout-logging"
    - DOCKERHUB_ADDL_MOUNT="nowaidavid/plex-media-addl-rclone-mount"
    - DOCKERHUB_NZBGET_POST_PROCESSING="nowaidavid/nzbget-post-processing-scripts"
    - DOCKERHUB_PLEX_UNICORN_TRANSCODER="nowaidavid/plex-unicorn-transcoder"
    - DOCKERHUB_RCLONE_ROTATE_SERVICE_ACCOUNT="nowaidavid/rclone-rotate-service-account"
    - DOCKERHUB_PM_BASE_TOOLS="nowaidavid/pm-base-tools"
    - DOCKERHUB_PM_PLEX_BASE="nowaidavid/pm-plex-base"


jobs:
  include:
    - stage: BuildPlexLoggingImage
      if: ((NOT (type IN (pull_request)) AND (commit_message in ('plex-redirect-stdout'))))
      script:
        # Build image
        - docker build --no-cache -f ./plex-redirect-stdout/Dockerfile -t ${DOCKERHUB_LOGGING}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB_LOGGING}:${TRAVIS_COMMIT} ${DOCKERHUB_LOGGING}:latest
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB_LOGGING}:latest
        - docker push ${DOCKERHUB_LOGGING}:${TRAVIS_COMMIT}
    - stage: BuildImagePlexAddlMount
      if: (NOT (type IN (pull_request)))
      script:
        # Build image
        - docker build --no-cache -f ./plex-additional-rclone-mount/Dockerfile -t ${DOCKERHUB_ADDL_MOUNT}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB_ADDL_MOUNT}:${TRAVIS_COMMIT} ${DOCKERHUB_ADDL_MOUNT}:latest
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB_ADDL_MOUNT}:${TRAVIS_COMMIT}
        - docker push ${DOCKERHUB_ADDL_MOUNT}:latest
    - stage: BuildImageNZBGetPostProcessing
      if: ((NOT (type IN (pull_request)) AND (commit_message in ('nzbget-post-processing-scripts'))))
      script:
        # Build image
        - docker build --no-cache -f ./nzbget-post-processing-scripts/Dockerfile -t ${DOCKERHUB_NZBGET_POST_PROCESSING}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB_NZBGET_POST_PROCESSING}:${TRAVIS_COMMIT} ${DOCKERHUB_NZBGET_POST_PROCESSING}:latest
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB_NZBGET_POST_PROCESSING}:${TRAVIS_COMMIT}
        - docker push ${DOCKERHUB_NZBGET_POST_PROCESSING}:latest
    - stage: BuildImagePlexUnicornTranscoder
      if: ((NOT (type IN (pull_request)) AND (commit_message in ('plex-unicorn-transcoder'))))
      script:
        # Build image
        - docker build --no-cache -f ./plex-unicorn-transcoder/Dockerfile -t ${DOCKERHUB_PLEX_UNICORN_TRANSCODER}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB_PLEX_UNICORN_TRANSCODER}:${TRAVIS_COMMIT} ${DOCKERHUB_PLEX_UNICORN_TRANSCODER}:latest
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB_PLEX_UNICORN_TRANSCODER}:${TRAVIS_COMMIT}
        - docker push ${DOCKERHUB_PLEX_UNICORN_TRANSCODER}:latest
    - stage: BuildImageRcloneServiceAccounts
      if: ((NOT (type IN (pull_request)) AND (commit_message in ('rclone-rotate-service-account'))))
      script:
        # Build image
        - docker build --no-cache -f ./rclone-rotate-service-account/Dockerfile -t ${DOCKERHUB_RCLONE_ROTATE_SERVICE_ACCOUNT}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB_RCLONE_ROTATE_SERVICE_ACCOUNT}:${TRAVIS_COMMIT} ${DOCKERHUB_RCLONE_ROTATE_SERVICE_ACCOUNT}:latest
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB_RCLONE_ROTATE_SERVICE_ACCOUNT}:${TRAVIS_COMMIT}
        - docker push ${DOCKERHUB_RCLONE_ROTATE_SERVICE_ACCOUNT}:latest
    - stage: BuildImagePMBaseTools
      if: ((NOT (type IN (pull_request)) AND (commit_message in ('pm-base-tools'))))
      script:
        # Build image
        - docker build --no-cache -f ./pm-base-tools/Dockerfile -t ${DOCKERHUB_PM_BASE_TOOLS}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB_PM_BASE_TOOLS}:${TRAVIS_COMMIT} ${DOCKERHUB_PM_BASE_TOOLS}:latest
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB_PM_BASE_TOOLS}:${TRAVIS_COMMIT}
        - docker push ${DOCKERHUB_PM_BASE_TOOLS}:latest
    - stage: BuildImagePMPlexBase
      if: ((NOT (type IN (pull_request)) AND (commit_message in ('pm-plex-base'))))
      script:
        # Build image
        - docker build --no-cache -f ./pm-plex-base/Dockerfile -t ${DOCKERHUB_PM_PLEX_BASE}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB_PM_PLEX_BASE}:${TRAVIS_COMMIT} ${DOCKERHUB_PM_PLEX_BASE}:latest
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB_PM_PLEX_BASE}:${TRAVIS_COMMIT}
        - docker push ${DOCKERHUB_PM_PLEX_BASE}:latest

