sudo: true

language: bash

services:
  - docker

env:
  global:
    - DOCKERHUB_LOGGING="nowaidavid/plex-media-server-stdout-logging"
    - DOCKERHUB_ADDL_MOUNT="nowaidavid/plex-media-addl-rclone-mount"
    - DOCKERHUB_NZBGET_POST_PROCESSING="nowaidavid/nzbget-post-processing-scripts"
    - DOCKERHUB_PLEX_UNICORN_TRANSCODER="nowaidavid/plex-unicorn-transcoder"

jobs:
  include:
    - stage: BuildPlexLoggingImage
      if: (NOT (type IN (pull_request)))
      script:
        # Build image
        - docker build --no-cache -f ./plex-redirect-stdout/Dockerfile -t ${DOCKERHUB_LOGGING}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB_LOGGING}:${TRAVIS_COMMIT} ${DOCKERHUB_LOGGING}:latest
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB_LOGGING}:latest
        - docker push ${DOCKERHUB_LOGGING}:${TRAVIS_COMMIT}
    - stage: BuildImagePlexAddlMount
      if: (NOT (type IN (pull_request)))
      script:
        # Build image
        - docker build --no-cache -f ./plex-additional-rclone-mount/Dockerfile -t ${DOCKERHUB_ADDL_MOUNT}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB_ADDL_MOUNT}:${TRAVIS_COMMIT} ${DOCKERHUB_ADDL_MOUNT}:latest
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB_ADDL_MOUNT}:${TRAVIS_COMMIT}
        - docker push ${DOCKERHUB_ADDL_MOUNT}:latest
    - stage: BuildImageNZBGetPostProcessing
      if: (NOT (type IN (pull_request)))
      script:
        # Build image
        - docker build --no-cache -f ./nzbget-post-processing-scripts/Dockerfile -t ${DOCKERHUB_NZBGET_POST_PROCESSING}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB_NZBGET_POST_PROCESSING}:${TRAVIS_COMMIT} ${DOCKERHUB_NZBGET_POST_PROCESSING}:latest
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB_NZBGET_POST_PROCESSING}:${TRAVIS_COMMIT}
        - docker push ${DOCKERHUB_NZBGET_POST_PROCESSING}:latest
    - stage: BuildImagePlexUnicornTranscoder
      if: (NOT (type IN (pull_request)))
      script:
        # Build image
        - docker build --no-cache -f ./plex-unicorn-transcoder/Dockerfile -t ${DOCKERHUB_PLEX_UNICORN_TRANSCODER}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB_PLEX_UNICORN_TRANSCODER}:${TRAVIS_COMMIT} ${DOCKERHUB_PLEX_UNICORN_TRANSCODER}:latest
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB_PLEX_UNICORN_TRANSCODER}:${TRAVIS_COMMIT}
        - docker push ${DOCKERHUB_PLEX_UNICORN_TRANSCODER}:latest

