sudo: true

language: bash

services:
  - docker

env:
  global:
    - DOCKERHUB_LOGGING="nowaidavid/plex-media-server-stdout-logging"
    - DOCKERHUB_ADDL_MOUNT="nowaidavid/plex-media-addl-rclone-mount"

jobs:
  include:
    - stage: BuildImage
      if: (NOT (type IN (pull_request)))
      script:
        # Build image
        - ls -alt
        - docker build --no-cache -f ./plex-redirect-stdout/Dockerfile -t ${DOCKERHUB_LOGGING}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB_LOGGING}:${TRAVIS_COMMIT} ${DOCKERHUB_LOGGING}:latest
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB_LOGGING}:latest
        - docker push ${DOCKERHUB_LOGGING}:${TRAVIS_COMMIT}
    - stage: BuildImageAddlMount
      if: (NOT (type IN (pull_request)))
      script:
        # Build image
        - ls -alt
        - docker build --no-cache -f ./plex-additional-rclone-mount/Dockerfile -t ${DOCKERHUB_ADDL_MOUNT}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB_ADDL_MOUNT}:${TRAVIS_COMMIT} ${DOCKERHUB_ADDL_MOUNT}:latest
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB_ADDL_MOUNT}:${TRAVIS_COMMIT}
        - docker push ${DOCKERHUB_ADDL_MOUNT}:latest
