sudo: true

language: bash

services:
  - docker

env:
  global:
    - DOCKERHUB="nowaidavid/plex-media-server-stdout-logging"

jobs:
  include:
    - stage: BuildImage
      if: (NOT (type IN (pull_request)))
      script:
        # Build image
        - ls -alt
        - docker build --no-cache -f ./plex-redirect-stdout/Dockerfile -t ${DOCKERHUB}:${TRAVIS_COMMIT} .
        - docker tag ${DOCKERHUB}:${TRAVIS_COMMIT} ${DOCKERHUB}:latest
        # Login to DockerHub
        - echo $DOCKERPASS | docker login -u $DOCKERUSER --password-stdin
        # Push all of the tags
        - docker push ${DOCKERHUB}:${TRAVIS_COMMIT}
        - docker push ${DOCKERHUB}:latest
