#!/usr/bin/with-contenv bash

umask 022

exec \
        s6-setuidgid root bash -c 'tail -f  "/config/Library/Application Support/Plex Media Server/Logs/Plex Media Scanner.log" | grep --line-buffered .  > /proc/1/fd/1'
