#!/usr/bin/with-contenv bash

apt update && \
apt-get install -y \
    python3 \
    python3-pip \
    python3-dev \
    g++ \
    && 
 pip3 install --no-cache-dir --upgrade pip setuptools wheel && \
 # PIP upgrade bug https://github.com/pypa/pip/issues/5221
 hash -r pip3 && \
 pip3 install --no-cache-dir --upgrade -r /plex_autoscan/requirements.txt && \
 # Remove dependencies
 apt-get purge -y --auto-remove \
   python3-dev \
   g++ && \
# Link python to python3
ln -s /usr/bin/python3 /usr/bin/python
 echo "**** cleanup ****" && \
 apt-get clean && \
 rm -rf \
	/tmp/* \
	/var/lib/apt/lists/* \
	/var/tmp/*

# Pull latest changes
echo "# plex_autoscan checking for updates"

if [ $GIT_UPDATE_AUTOSCAN == "true"]
    git -C /plex_autoscan pull
fi

# Create and chown plex_autoscan config dir
mkdir -p /autoscan
chown -R abc:abc /autoscan /plex_autoscan
