name: "Build LSIO Docker Mods"

on: push

jobs:
  build-nzbget-post-processing-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: nzbget-post-processing-scripts
          dockerfile: nzbget-post-processing-scripts/Dockerfile
          addLatest: true
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT_TOKEN }}

  build-plex-additional-rclone-mount:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: plex-additional-rclone-mount
          dockerfile: plex-additional-rclone-mount/Dockerfile
          addLatest: true
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT_TOKEN }}

  build-plex-redirect-stdout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: plex-redirect-stdout
          dockerfile: plex-redirect-stdout/Dockerfile
          addLatest: true
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT_TOKEN }}

  build-plex-unicorn-transcoder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: plex-unicorn-transcoder
          dockerfile: plex-unicorn-transcoder/Dockerfile
          addLatest: true
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT_TOKEN }}

  build-pm-base-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: pm-base-tools
          dockerfile: pm-base-tools/Dockerfile
          addLatest: true
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT_TOKEN }}

  build-pm-unicorn-ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: pm-unicorn-ffmpeg
          dockerfile: pm-unicorn-ffmpeg/Dockerfile
          addLatest: true
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT_TOKEN }}

  build-rclone-rotate-service-account:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: rclone-rotate-service-account
          dockerfile: rclone-rotate-service-account/Dockerfile
          addLatest: true
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT_TOKEN }}
